export const APP_ROUTES = {
  maintenance: "/maintenance",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  confirmEmail: "/confirm-email",
  adminLogin: "/admin/login",
  home: "/",
  journey: "/journey",
  reviews: "/reviews",
  about: "/about",
  privacy: "/privacy",
  contact: "/contact",
  donation: "/donation",
  hallOfHonor: "/hall-of-honor",
  upload: "/upload",
  history: "/history",
  assessmentCreditDetails: "/credits",
  /* `/credits` is the canonical owner-facing assessment credits surface.
     Keep the legacy `globalCredits` alias until older imports/bookmarks are fully retired,
     but prefer `assessmentCreditDetails` in new code so route ownership stays explicit. */
  globalCredits: "/credits",
  assessment: "/assessment",
  assessmentCredits: "/assessment/credits",
  lectureSummary: "/lecture-summary",
  infographic: "/infographic",
  settings: "/settings",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminReviews: "/admin/reviews",
  adminPlatformUsage: "/admin/platform-usage",
} as const;
