export const APP_ROUTES = {
  maintenance: "/maintenance",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  confirmEmail: "/confirm-email",
  adminLogin: "/admin/login",
  home: "/",
  journey: "/journey",
  about: "/about",
  privacy: "/privacy",
  contact: "/contact",
  donation: "/donation",
  hallOfHonor: "/hall-of-honor",
  upload: "/upload",
  history: "/history",
  globalCredits: "/credits",
  assessment: "/assessment",
  assessmentCredits: "/assessment/credits",
  lectureSummary: "/lecture-summary",
  infographic: "/infographic",
  settings: "/settings",
  admin: "/admin",
  adminUsers: "/admin/users",
} as const;
